project:
  type: website

website:
  sidebar:
    style: "floating"
    contents:
      - href: index.qmd
        text: "{{< meta i18n.nav_dashboard >}}"
      - section: "{{< meta i18n.section_strategy >}}"
        contents:
          - 01_strategy_okrs/okr_dashboard.qmd
          - 01_strategy_okrs/value_stream.qmd
      - section: "{{< meta i18n.section_initiating >}}"
        contents:
          - 02_initiating_pmbok/business_case.qmd
          - 02_initiating_pmbok/project_charter.qmd
          - 02_initiating_pmbok/stakeholder_reg.qmd
      - section: "{{< meta i18n.section_planning >}}"
        contents:
          - 03_planning_scope/requirements.qmd
          - 03_planning_scope/wbs.qmd
          - 03_planning_scope/wbs_dictionary.qmd
      - section: "{{< meta i18n.section_execution >}}"
        contents:
          - 04_agile_execution/product_backlog.qmd
          - 04_agile_execution/roadmap.qmd
      - section: "{{< meta i18n.section_control >}}"
        contents:
          - 05_monitoring_control/risk_register.qmd
          - 05_monitoring_control/change_log.qmd

