spark.jars.packages=org.apache.iceberg:iceberg-spark-runtime-4.0_2.13:1.10.1 
spark.eventLog.dir=file:/root/SPARK/spark-events
spark.eventLog.enabled=true
spark.hadoop.fs.s3a.endpoint=http://localhost:8000
spark.hadoop.fs.s3a.access.key='AKIAJPG2FGB3ZE4VLNGQ'
spark.hadoop.fs.s3a.secret.key='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'
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.sql.catalog.lakefs=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.lakefs.type=hadoop
spark.sql.catalog.lakefs.warehouse=s3a://iceberg/main/warehouse
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.debug.maxToStringFields=1000

spark.driver.memory=4g
spark.driver.maxResultSize=4g
spark.executor.memory=4g

spark.local.dir=/home/TMP

spark.plugins=com.nvidia.spark.SQLPlugin
