core :
  ensure_directories : true

paths :
  work : work
  data : data
  checkpoint : checkpoint
  logs : logs

logging :
  file : subsea.log

storage :
  type : s3

runtime :
  enable_gpu : true

pipeline :
  Corals :
    bucket : analise-dados
    prefix : projeto-ia-submarina/ia-frente-ambiental
