project:
  title: "OKRs"
  output-dir: build

toc: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
  pdf:
    toc: true
    toc-depth: 3
    number-sections: true
    documentclass: article
    fontsize: 11pt
    geometry: margin=1in


