project:
  type: manuscript
  output-dir: build

toc: true

resources:
  - style.css
  - contents/explanation.qmd
  - contents/okr/okr.qmd
  #- contents/okr/issue.qmd
  - contents/okr/issue-kr1.qmd
  - contents/okr/issue-kr2.qmd
  - contents/okr/issue-kr3.qmd
  - contents/okr/issue-kr4.qmd
  - contents/okr/issue-kr5.qmd
  - contents/okr/issue-kr6.qmd
  #- contents/explanation.qmd
  #- contents/presentation-plan.qmd
  #- contents/package.qmd
  #- contents/ARCH.qmd

manuscript:
  article: index.qmd

  notebooks:

    - notebook: contents/okr/okr.qmd
      title: '01 - OKR'

    #- notebook: contents/okr/issue.qmd
    #  title: '02 - issue'

    - notebook: contents/okr/issue-kr1.qmd
      title: '02 - issue - KR1'

    - notebook: contents/okr/issue-kr2.qmd
      title: '02 - issue - KR2'

    - notebook: contents/okr/issue-kr3.qmd
      title: '02 - issue - KR3'

    - notebook: contents/okr/issue-kr4.qmd
      title: '02 - issue - KR4'

    - notebook: contents/okr/issue-kr5.qmd
      title: '02 - issue - KR5'

    - notebook: contents/okr/issue-kr6.qmd
      title: '02 - issue - KR6'

    #- notebook: contents/presentation-plan.qmd
    #  title: '03 - Presentation Plan'

    #- notebook: contents/package.qmd
    #  title: '04 - Package'

    #- notebook: contents/ARCH.qmd
    #  title: '04 - ARCHITECTURE'

#notebook-links: false

#title-block-banner: false

css: style.css

format:
  html:
    comments:
      hypothesis: false
    theme:
      light: flatly
      dark: darkly
    mermaid:
      theme: dark
    toc: true
    toc-location: left
    page-layout: full
  
  #docx: default
  #jats: default
  pdf:
    documentclass: article
    #number-sections: true
    code-fold: true
    classoption: "margin=1in"
    header-includes:
      - \setlength{\oddsidemargin}{0in}
      - \setlength{\evensidemargin}{0in}
      - \setlength{\textwidth}{6.5in}
      - \setlength{\topmargin}{0in}
      - \setlength{\textheight}{9in}
    page-size: a4
    margin: 1in
  #revealjs:
  #  theme: simple
  #  smaller: true
  #  scrollable: true
  #  output-file: document-revealjs.html

execute:
  freeze: false



