features:
  - image_stats
  #- histogram
  #- lbp
  #- exif

paths:
  espadarte: s3a://noaa-auv/main/NOAA-AUV/ESPADARTE
  viola: s3a://noaa-auv/main/NOAA-AUV/VIOLA

datasets:
  #- name: espadarte
  #  cruise: 6000702270
  #  dive: COM20240425
  #  read:
  #    file_format: binaryFile
  #    glob_filter: "*.tif"
  #    recursive: true
  #    sample_fraction: 0.0025

  - name: viola
    cruise: 6000713538
    dive: ''
    read:
      file_format: binaryFile
      glob_filter: "*.jpg"
      recursive: true
      sample_fraction: 0.0025
