apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s12190-descomissionamento
  description: (Alterar) Descrição do módulo descomissionamento da aplicação S12190
  annotations:
    github.com/project-slug: petrobrasbr/s12190-descomissionamento
    petrobras.com.br/vertical: aid
#    backstage.io/techdocs-ref: dir:.
#  tags:
#    - exemplo
#  links:
#    - url: https://exemplo.petrobras.petrobras.com.br
#      title: Exemplo
spec:
  type: website
  owner: default/s12190_maintain_team
  lifecycle: Em produção
  system: s12190

